#!/bin/bash

SCRIPT_DIR="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

# Source directory is the directory containing the CMakeLsists.txt script
SOURSE_DIR=$SCRIPT_DIR/build/CMake
# Build directory is going to contain project files generated by CMake.
BUILD_DIR=$SOURSE_DIR/gnumake

# Create the build directory if it doesn't already exist.
mkdir -p $BUILD_DIR
# Generate project files
cmake -S $SOURSE_DIR -B $BUILD_DIR

# Build the targets defined in the project files
cmake --build $BUILD_DIR --config Debug

# Run tests
cd $BUILD_DIR && \
ctest -C Debug --output-on-failure