name: Unit Tests

on:
  push:        # This workflow is triggered by pushing to a git branch specified below
    branches:
      - devel  # Project's branch name

jobs:
  test-on-ubuntu-linux:
    runs-on: ubuntu-latest  # Runner (execution environment)

    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2  # Pre-built GitHub Actions workflow called "actions/checkout" with version 2 (v2)

    - name: Set Up GNU Make
      run: |
        sudo apt-get -y install make
      shell: bash

    - name: Build Project
      run: |
        make
      working-directory: ${{ github.workspace }}/build/GNUMake  # the directory in which the subsequent steps of the workflow will be executed; github.workspace - the root of the repository

    - name: Run Unit Tests
      run: |
        make test
      working-directory: ${{ github.workspace }}/build/GNUMake

  test-on-windows:
    runs-on: windows-latest  # Runner (execution environment)

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up CMake
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
        shell: powershell

      - name: Create Build Directory
        run: |
          mkdir win
        working-directory: ${{ github.workspace }}/build/CMake

      - name: Configure CMake
        run: |
          cmake -S . -B ./win
        working-directory: ${{ github.workspace }}/build/CMake

      - name: Build Project
        run: |
          cmake --build . --config Debug
        working-directory: ${{ github.workspace }}/build/CMake/win

      - name: Run Unit Tests
        run: |
          ctest -C Debug --output-on-failure
        working-directory: ${{ github.workspace }}/build/CMake/win
